### ISSUE TITLE
Code Error in time->run every code line

### ISSUE THREAD

**Issue by grumpycoder100** [grumpycoder100/colourception#2]
![image](https://cloud.githubusercontent.com/assets/12503671/21351407/5714fb88-c6f7-11e6-9f75-336db6680519.png)

Please fix this ASAP @grumpyspaceman100 . Thanks. I will upload the required art assets soon.

**Comment by grumpyspaceman100** [comment]
Just noticed the code error. Sorry for that @grumpycoder100! Fix is coming up very soon.
